spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/med-inv
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 20
      minimumIdle: 10
      autoCommit: true
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB