spring:
  security:
    user:
      password: root

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
    root: INFO

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}